### ISSUE TITLE
Basic Setup.

### ISSUE THREAD

**Issue by KaneHart** [pdinklag/MinecraftStats#1]
Is there a basic guide on setup. I'm finding my biggest issue is I don't know how to say dump server stats or retrive the server stats. I know the player dat files are UUID's now not sure if they go into the data or raw folder if I should even be creating them etc.

Thanks.

**Comment by Slab30** [comment]
If you are running linux you have to copy the content of your /path/to/world/stats folder to the /path/to/MinecraftStats/raw folder and then "cd" to the /path/to/MinecraftStats/update.php folder and "run php5 update.php".

You can set up a cronjob running a script like this:

#!/bin/bash

cd /path/to/MinecraftStats
rsync -rt --delete /path/to/world/stats/ /path/to/MinecraftStats/raw/
php5 update.php

**Comment by pdinklag** [comment]
Sorry for the lack of documentation, it was never really meant to be a public project.

But since there seems to be increasing interest, I'll look into writing one. Slab's descritpion works, but you'll still lack icons (which I didn't put into the repository for legal reasons - I'll look into that, too).
