### ISSUE TITLE
Updating

### ISSUE THREAD

**Issue by Chow86** [pdinklag/MinecraftStats#10]
Hi,
Thanks for adding a great feature for servers.

Am I correct in my understanding that, in order to update the stats, I must move the contents of the stats dir from the server to the raw dir.

When I do this is shows that every user was last online at the time update.php was ran. I noticed that your website shows different times for every player.

Regards
Matt

**Comment by pdinklag** [comment]
The script uses the files' timestamps to determine the "last online" property, because Minecraft doesn't explicitly store this information.

I suppose that when you copy the files, the timestamps are changed to the time the copy is done.

If you are under linux, add the `--preserve=timestamps` option (see [man cp](http://man7.org/linux/man-pages/man1/cp.1.html)). As the option's name suggests, this will preserve the file timestamps and the "last online" information should be correct again.

**Comment by Chow86** [comment]
Thanks for the suggestion. Since my server and website are on different machines, I was able to use filezilla to preserve the time stamp on upload
