### ISSUE TITLE
exclude players

### ISSUE THREAD

**Issue by end-user** [pdinklag/MinecraftStats#110]
For one reason or another (e.g. admins that are on all the time), it would be helpful to have a way to exclude players from the count.  Perhaps an `exclude.json` or just a list of guids?

**Comment by pdinklag** [comment]
Do you specifically ask this for banned players, i.e., could I use the server's `banned-players.json`, because that would make sense?
Or are you also asking to exclude specific players for other reasons?

**Comment by end-user** [comment]
Banned players is a great idea, but I was thinking of other reasons, specifically if there are OPs who can easily exceed others' achievements.  Of course, if you exclude those in `banned-players.json` it'd be just as easy to exclude `ops.json` as well.  That covers my use case, but it might be nice to have a third list also.

**Comment by pdinklag** [comment]
OK, good to know!
Excluding banned players should probably be enabled by default, and excluding ops sounds like a reasonnable option.

Concerning an additional list, I'll consider. Right now, all configuration happens via the command-line, so it would be a bit inconsistent to just add a JSON file for additional configuration. So that needs some thinking about maybe configuring Minecraft Stats via a JSON file in the future.

**Comment by pdinklag** [comment]
Added the `excludeBanned` and `excludeOps` settings for excluding banned players and ops, as well as `exclude` that accepts an additional list of UUIDs to exclude.
