### ISSUE TITLE
Auto-update statistics

### ISSUE THREAD

**Issue by Sky-Evil** [pdinklag/MinecraftStats#122]
Sorry, I have another question. I'm trying to set up auto update using crontab, but I can't get it
I used:
*/5 * * * * python3 /home/admin/web/stats.oldcraft-mc.ru/public_html/python3 update.py config.json
as well as
*/5 * * * * /usr/bin/python3 update.py /home/admin/web/stats/public_html/config.json
Perhaps you have an example of how this should work. I really tried to figure it out on my own, but it didn't work out for me (

**Comment by pdinklag** [comment]
I don't have an example because crontab has been around since 1975 and is really well [documented](https://www.man7.org/linux/man-pages/man5/crontab.5.html). You can find countless tutorials and examples out there, way better than what I could ever do. What you enter is completely a matter of when you want it to run and where you installed it.

> */5 * * * * python3 /home/admin/web/stats.oldcraft-mc.ru/public_html/python3 update.py config.json

This does not make much sense, you are passing python3 to python3?

> */5 * * * * /usr/bin/python3 update.py /home/admin/web/stats/public_html/config.json

Note that cronjobs, by default, are executed in the user's _home_ directory and you may want to do a `cd` first to set the working directory.

I have no idea about your system and can only take a wild guess that this is it if you want it to run every 5 minutes:
``` 
*/5 * * * * cd /home/admin/web/stats/public_html; python3 update.py config.json
```
If this doesn't work, please make sure the paths are correct and maybe read about cron.

**Comment by Sky-Evil** [comment]
*/5 * * * * cd /home/admin/web/stats.oldcraft-mc.ru/public_html; python3 update.py config.json

Your version works, thanks!
