### ISSUE TITLE
Floodgate players not listed

### ISSUE THREAD

**Issue by alexstore06** [pdinklag/MinecraftStats#125]
My Java server (1.16.4) uses Geyser and Floodgate to allow Bedrock players. Usernames should look like, and are listed in the whitelist as, *username. UUIDs are created by Floodgate and look like this: 00000000-0000-0000-0009-01f950bbeb84 (my Floodgate UUID). I use this tool: https://floodgate-uuid.heathmitchell1.repl.co/
Only Java players appear to be showing up on my site. I can provide the site if required.
When running update.py, I get this:
```
updating profile for 00000000-0000-0000-0009-01f950bbeb84 ...
empty Mojang API response for https://sessionserver.mojang.com/session/minecraft/profile/0000000000000000000901f950bbeb84
        excluding invalid player 00000000-0000-0000-0009-01f950bbeb84
```
Will Floodgate UUID support ever be added?

**Comment by pdinklag** [comment]
I never heard about Floodgate so far. In any event, MinecraftStats looks up player names and skins via Mojang's API, and that only works for UUIDs associated to valid Mojang accounts. I guess that Bedrock does not use them and that's what Floodgate is for?

If there is any feasible way to get a username (and maybe skin) from a floodgate UUID, I can look into supporting them.

**Comment by alexstore06** [comment]
As of right now, Geyser doesn't support Bedrock skins, although I hear that they're working on it.
Are only the UUIDs provided with the stats JSONs, instead of UUIDs and usernames? I don't think you can go from Floodgate UUID to Bedrock username, but I'll see if I can find something.

**Comment by pdinklag** [comment]
The only place where Minecraft stores usernames is in `usercache.json`, but that is only temporary. The entries expire after a while and from that point, the only way to find out any user info, including the name, is by looking up the UUID. MinecraftStats does try to use the usercache, but since you're seeing that message, there is no entry for that UUID in there. It may have expired, but I'm also not sure if Minecraft servers even include these non-Mojang UUIDs in the usercache in the first place.

So yeah, some way to revert Floodgate UUIDs to a username would be needed.

**Comment by alexstore06** [comment]
I've actually been moving just the stats folder and server.properties file using FTP to my web server, so let me try adding the usercache to that. Will update later. Thanks!

**Comment by alexstore06** [comment]
That seems to have fixed my problem. Thank you so much!

**Comment by pdinklag** [comment]
Good to know!
Bear in mind that players who haven't joined your server in a while won't be added until they log back on, because as mentioned, the usercache only stores them for 30 days.
