### ISSUE TITLE
unsupported data version 0 for ...

### ISSUE THREAD

**Issue by phynias** [pdinklag/MinecraftStats#127]
Sorry for be ignorant about minecraft. setting this up for a friend and i am having a problem.
 
when i try and run the update i get the following
`unsupported data version 0 for b633308f-dddc-44e3-a581-fcc8faa82b1e`

it's loading /data/FeedTheBeast/world/stats/b633308f-dddc-44e3-a581-fcc8faa82b1e.json
and the file contents are
`{   'stat.damageTaken': 400,
    'stat.deaths': 1,
    'stat.leaveGame': 7,
    'stat.mineBlock.chancecubes.chance_cube': 1,
    'stat.mineBlock.minecraft.tallgrass': 3,
    'stat.pickup.botania.manaresource': 6,
    'stat.pickup.everlastingabilities.ability_bottle': 1,
    'stat.playOneMinute': 11735,
    'stat.sneakTime': 43,
    'stat.timeSinceDeath': 4029,
    'stat.walkOneCm': 2062
}`

so i don't see 'DataVersion' in there or really anywhere in any files in game dir.

thanks.

**Comment by pdinklag** [comment]
The reason you don't see a data version is because that was only introduced with Minecraft 1.13 (more precisely with snapshot [17w47a](https://minecraft.gamepedia.com/Java_Edition_17w47a)), and looking at those stat names, you're dealing with an older version of Minecraft. Said snapshot was released late 2017 and older versions are not supported at all.

You have two options:
1. Switch to a new version of Minecraft. This is probably what you'll want to do. I don't know much about FTB, but it looks like it's still active, so there should be a version running on a newer Minecraft.
2. Use a [very very old](https://github.com/pdinklag/MinecraftStats/tree/347062d771640e141a1b9eb9b08a8724922bfac2) version of Minecraft Stats from 2015. It's still based on PHP and I won't offer help for it anymore.
