### ISSUE TITLE
Event summary page is displaying the wrong top score

### ISSUE THREAD

**Issue by cunhar** [pdinklag/MinecraftStats#198]
![image](https://user-images.githubusercontent.com/1693935/159355380-80961045-5d43-4d18-913d-3be3d2ca8a7a.png)
https://www.hoobs.live/minecraft/#events
![image](https://user-images.githubusercontent.com/1693935/159355444-8f137462-4440-476f-aaed-706d85d730c4.png)
https://www.hoobs.live/minecraft/#event:spring_2022

It seems to be showing the total before the last update ran. 

-- Ricardo

**Comment by cunhar** [comment]
![image](https://user-images.githubusercontent.com/1693935/159355945-8fb916fa-6c93-4549-b2aa-952221fb9c74.png)

it also seems to be different in the awards page.

**Comment by pdinklag** [comment]
I can confirm that this is always behind by one update and other bugs may occur as well because of some twisted logic.

---
Just to explain (and as a note to self) why there are so many issues with events: there are two conflicting "opinions" that MinecraftStats has of an event having started or ended. One is concerned about the times as defined in the config, the other about what data is available from previous updates. The reason is basically that updates may happen at any point, completely out of sync with the times defined in the config. The logic needs a serious overhaul, which I will look into.

This particular bug comes from #195, which fixed some issues, but really only added more faulty logic over already faulty logic. Fixing it is not trivial right now, but will be once the core problems are solved.

**Comment by pdinklag** [comment]
Events have been re-implemented in v3.0.0.
This bug should be resolved, please reopen if not.
