### ISSUE TITLE
Semicolon instead of plus sign

### ISSUE THREAD

**Issue by JeftaDirksen** [pdinklag/MinecraftStats#2]
Hi pdinklag,

It's already some time ago i noticed the following error, but hadn't reported is yet.

In the config-stats.php on line 398 the semicolon at the end of the line should be a plus sign i guess.

For the rest i really like you project.
I use the code of the score for the Suspect award for banning players from my server, the only thing i might change in the future is that the score will always decrease over time, not just the first 4 hours of play time. Oh and i might add a compare between stone mined and diamond mined to detect XRay cheaters.

Thnx,

Jefta

**Comment by pdinklag** [comment]
You are right, thanks for reporting!

Also thanks for the feedback, and feel free to modify as you wish, cool too see it in use! If you have useful additions to Suspect, feel free to share! But as a little advice, don't ban just by the Suspect score, do look at some raw stats and maybe spectate the player ingame. ;)

By the way, I have just committed all the images (I left them out due to possible legal issues, but there really aren't any) and will try to put up some kind of documentation in the near future.
