### ISSUE TITLE
Fresh install, fails after the first 32 users (I have 400k+)

### ISSUE THREAD

**Issue by TomLewis** [pdinklag/MinecraftStats#207]
Hello! Fresh install here!
Fails after the first 32 users, I have over 400k users.

https://gist.github.com/TomLewis/5e41a8573b6b55e69b1d7a092a57b331

My server is 10 years old, so stats have been updated over many minecraft versions, currently using 1.18.2.

**Comment by pdinklag** [comment]
Hi!
Hm, old files shouldn't be a problem, the log looks more like one of your JSON files is corrupted. This shouldn't crash the whole thing, though, so I'll add a guard there that will print a more peaceful warning for files that cannot be read for whatever reason.

**Comment by TomLewis** [comment]
Brilliant, thanks! I will eagerly anticipate an update! 
Is there a place to ask questions?

- Can I customize the look and feel? Is it possible to swap themes? are there any themes out there to choose from? I would love to change the design to bootstrap to fit in with my website/strip all design so I can embed it somehow with Wordpress.
- Can as estimated timer be added? I have no idea how long a once over will take on 400k users
- When updating do stat files get ignored if they haven't changed since they were last updated, to speed up updating the rest of the users?

**Comment by pdinklag** [comment]
Please take questions to Discord, you can find the invite in the "About" section. To that end, I'll answer very briefly, and we can discuss details offline.

- It's all just HTML and CSS - everything can be customized, but you have to do it by yourself.
- Feel free to open an issue suggesting a progress display. Usually, you do these updates automatically and don't care. Only the first update takes long, because *all* player names and skins need to be polled from the Mojang API.
- No, and I'll open an issue about that myself. However, the reason is that this has never been a problem. Subsequent updates are much (much!) faster because the Mojang API queries need only be done for new players.
