### ISSUE TITLE
README.TXT award not working

### ISSUE THREAD

**Issue by Lagger625** [pdinklag/MinecraftStats#31]
The stat says nobody has placed any sign, but almost everyone in the server, including me, clearly did.

**Comment by pdinklag** [comment]
Hm, may be related to the fact that I'm keeping this up to date with the 1.14 snapshots and I'm not sure when they introduced signs of different colors. But this would be fixable.

Can you please provide the following:
* Your Minecraft server version.
* Your statistics JSON file (found in `world/stats/<your-guid>.json` - maybe put it in a gist because it's probably rather long)?

**Comment by pdinklag** [comment]
Should be fixed! :-)
