### ISSUE TITLE
Performance Issues / Browser crash

### ISSUE THREAD

**Issue by Trikolon** [pdinklag/MinecraftStats#65]
First of all, great project, keep it up! I have some feedback concerning performance:

My server has around 85,000 player stat files, thus loading the player page takes a very long time, consumes a lot of system resources and sometimes even crashes the browser.

If you want to try: https://stats. tallcraft.com/#players (Can crash your browser)

**Comment by pdinklag** [comment]
I really appreciate you trying this on a big server! 👍 
You're facing the effects of me developing it against a small instance, so it's not really surprising. It's very good to have your instance now to try and get it working on a larger scale.

I see the (zipped) database takes up over 6MB already which is something I'll try to improve. The large file causes a rather long initial loading time because the client needs it.

In the players list, I suppose that's where pagination is absolutely needed at some point so it won't try and display _all_ players at once.

**Comment by Trikolon** [comment]
Sounds great. 
How about loading data on demand?
Also, modern web servers use good compression algorithms, I'm not sure if the archive is even needed.

**Comment by pdinklag** [comment]
Most data is already loaded on demand, e.g. the award rankings or a single player's statistic.

The biggest part of the `db.json` is a UUID to player name and skin mapping for quick display. This isn't a big issue, it's just that the data is stored in a very verbose JSON form and may be shrinked somehow. The GZIP compression will already take care of a lot of redundancy but apparently it's not quite enough, so I'll have to think of something here and I got some ideas.

> How about loading data on demand?

That's practically what I'd achieve by pagination for these long lists. Award rankings and a single player's statistics are already loaded only when you click on them. The player list is a global thing though and I believe splitting it into pages should do the trick here.

**Comment by pdinklag** [comment]
OK, I spent some thoughts and got a plan to solve this. I cannot tell when I get to it, it's a bigger change, but I see it's absolutely necessary. This comment will mainly serve as a reference for myself, so don't worry if things get technical below.

The core of the issue here is not the amount of data, but that server and client data are mixed in `db.json`. There's quite some info that only the server (`update.py`) needs and the client shouldn't have to bother with it. So the idea is to split `db.json` up and make the "load on demand" part more lightweight:

- The list of all player profiles and their last update times will go into a `profiles.json` file. The client will never need this.
- Currently, _all_ player profiles are stored in `db.json`. This is not necessary - for display of the main page, it suffices to store only the profiles of the award holders. This will make the file size independent of the number of players and depend only on the number of awards.
- For the Hall of Fame, an extra `hof.json` file will contain all profiles needed for that. It will only be downloaded when the HoF page is loaded (unlike now).
- The player list is the trickiest part. In the client, it will be paginated and on the server, the list will be fragmented into multiple JSON files so the client doesn't have to download all of them at once. The challenge here is that in the client, you can either show or hide inactive players, so pages on the client side do not necessarily match fragments on the server side. A dynamic loader would have to be implemented to handle this. An alternative solution, which may work better (= faster in the client) in fact, would be to have two sets of fragments: one containing inactive players and the other containing active players only.

**Comment by pdinklag** [comment]
OK, I have done some work on this and a large player count should not matter anymore.
Could you give the [`split-db`](https://github.com/pdinklag/MinecraftStats/tree/split-db) branch a try?

**Comment by pdinklag** [comment]
The changes have now been incorporated in the main branch.
Please somebody confirm that performance is improved.

**Comment by Trikolon** [comment]
Thanks for the update! Seems to work great.
https://stats.tallcraft.com/

**Comment by pdinklag** [comment]
Awesome, glad to hear! 😄 

I'm not very happy about the pagination for inactive players though, 46 in a row seems kinda much. Will see what I can do!
