### ISSUE TITLE
Question about dyes

### ISSUE THREAD

**Issue by lukeeexd** [pdinklag/MinecraftStats#66]
Would this track light_blue_dye too? Since its "minecraft:*_dye" but light blue has 2 underscores

Also difference between +_dye and *_dye?

And finally. Below code will it track furnace made dyes? if not any idea how to add that?

```from mcstats import mcstats

mcstats.registry.append(
    mcstats.MinecraftStat(
        'craft_dye',
        {
            'title': 'Chemist',
            'desc': 'Dyes crafted',
            'unit': 'int',
        },
        mcstats.StatSumMatchReader(
            ['minecraft:crafted'],
            ['minecraft:.*_dye'])
    ))```

**Comment by pdinklag** [comment]
It matches [regular expressions](https://docs.python.org/3/library/re.html), the number of underscores doesn't matter. In this case, either `+` (at least one character) or `*` (any number of characters) would do the same. Anyway, read up on regular expressions concerning that.

> Below code will it track furnace made dyes?

I don't know, you'll have to try. And if it works - does it also work if the furnace is attached to a hopper? Because that's the reason I didn't add these stats, afaik they're not considered, and many smelt with hoppers only.

**Comment by lukeeexd** [comment]
Ya doesnt track dyes made by smelting in furnace or if taken out by a hopper

**Comment by pdinklag** [comment]
OK, then it shouldn't be a statistic in my opinion until Mojang changes this.
