### ISSUE TITLE
Bungeecord (more servers)

### ISSUE THREAD

**Issue by synexTG** [pdinklag/MinecraftStats#99]
Hey,

is it possible to connect more than one server? Maybe more instances that are connecting to the same database?

kind regards

**Comment by pdinklag** [comment]
I'm unaware of how BungeeCord works really, how can I imagine the situation?

I imagine that there multiple `stats` directories with json files for players, one for each server? If so, where are they located: on a single machine or is each server located on a different machine? What exactly do you mean by "connecting to the same database"?

**Comment by TricityGaming** [comment]
A simple BungeeCord network is on a single machine, meaning there are several individual servers that are simply connected. The data would then have to be combined. Each server behaves like a server without BungeeCord.

I like your system and would like to combine all stats.

**Comment by pdinklag** [comment]
OK, so what's practically missing is some kind of merging of the player data from multiple servers into one for each player. For most stats, computing the sum of all servers should do the trick.

I shall do this the next time I work on the project! 🙂

**Comment by pdinklag** [comment]
Some implementation keynotes, as I've just been asked about this again:

* Instead of just looking at one `stats` directory to gather available player IDs, all servers have to be checked.
* For proper usercache support (needed e.g. for Floodgate), the `usercache.json` of all servers need to be considered.
* If ops are excluded, all servers' `ops.json` files need to be considered.
* Before actually processing player stats, their stat JSON files from all servers needs to be merged. This is the heavy lifting part that may or may not be very simple. It should not implemented in a way that needs updating for every server version, so hardcoding is not an option, at all.

**Comment by pdinklag** [comment]
You can now specify any number of servers in the configuration as documented [here](https://github.com/pdinklag/MinecraftStats#combining-multiple-servers).

Currently, stats from all servers are added up for each player. For the Explorer award, the discovered biomes are properly merged and counted uniquely.

**Comment by mercurialmusic** [comment]
Thank you for this! Very exciting. A question on syntax, though - how should worldName be provided when the main world name is different across servers? Will a similar array suffice, e.g. `"worldName": "world1,world2,world3"` ?

**Comment by pdinklag** [comment]
Hah, I was thinking about it and thought "well, why would people have different world names"?
So right now, this is not implemented, but that'll be a quick addition. I will change the JSON syntax then, however, because a second array would be too error-prone (and 20th century style).

**Comment by pdinklag** [comment]
Alright, it has been updated, see [here](https://github.com/pdinklag/MinecraftStats#combining-multiple-servers).
Let me know if that fixes the issues @mercurialmusic !

**Comment by mercurialmusic** [comment]
Seems to be working great, thanks!
